# ローカルサーバ（Vagrantで配布されているものを再現）
version: '3.8'
services:
  sftp-server:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "22:22"
    volumes:
      - ./path/to/sftp_data:/home/vagrant
    environment:
      - SFTP_USERS=vagrant:vagrant:1001
    restart: always

  web-server-m1:
    image: nginx
    container_name: web_server_m1
    ports:
      - "8081:80"
    volumes:
      - ./path/to/sftp_data/m1/public:/usr/share/nginx/html
    restart: always

  web-server-m2:
    image: nginx
    container_name: web_server_m2
    ports:
      - "8082:80"
    volumes:
      - ./path/to/sftp_data/m2/public:/usr/share/nginx/html
    restart: always
